Neos:
  Neos:
    Ui:
      frontendConfiguration:
        Carbon.ColorPicker.OKLCH:
          # Set the mode of the color picker. Possible values are: 'oklch', 'hex', 'coords', 'all'
          mode: 'all'
          # Show preset selector
          showPresets: true
          # Show input field for hex input
          showHexInput: true
          # Show color picker
          showPicker: true
          # Show slider to set the lightness
          showLightness: false
          # Show slider to set the luminance
          showLuminance: false
          # The precision of the OKLCH color picker. Set to 0 to disable rounding and use the raw values.
          precision: 5
          # Collapse the color picker (enables only when showPicker is true)
          collapsed: false
          # The name of the custom property. Only used when mode is set to 'all'
          customPropertyName: 'color'
          # Set the color contrast threshold for the color name output. Value between 0 and 1
          # Depend on the luminance, the text will be black or white
          contrastThreshold: 0.6
          # The presets are based on https://tailwindcss.com/docs/colors with the key 500
          # false and null values get filtered out
          presets:
            slate: '#62748e'
            gray: '#6a7282'
            zinc: '#71717b'
            neutral: '#737373'
            stone: '#79716b'
            taupe: '#7c6d67'
            mauve: '#79697b'
            mist: '#67787c'
            olive: '#7c7c67'
            red: '#fb2c36'
            orange: '#ff6900'
            amber: '#fd9a00'
            yellow: '#efb100'
            lime: '#7ccf00'
            green: '#00c951'
            emerald: '#00bc7d'
            teal: '#00bba7'
            cyan: '#00b8db'
            sky: '#00a6f4'
            blue: '#2b7fff'
            indigo: '#615fff'
            violet: '#8e51ff'
            purple: '#ad46ff'
            fuchsia: '#e12afb'
            pink: '#f6339a'
            rose: '#ff2056'
